jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: lsb_release -a
      - run: docker run -t -d --name test_docker_persistent alekzonder/puppeteer:latest bash
name: build
on:
  push:
    branches:
      - "**"
